# Generated by Django 3.1.3 on 2020-11-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUsers',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
